// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq6CiS1IIQmcSjLwvhiu8mvrarKiyURqo',
    appId: '1:221510305970:web:42fb33a7936294957161ab',
    messagingSenderId: '221510305970',
    projectId: 'flicko-82e0a',
    authDomain: 'flicko-82e0a.firebaseapp.com',
    storageBucket: 'flicko-82e0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CfkBqgGrsSq2YRDzsjkuJX-jV_0OwUE',
    appId: '1:221510305970:android:7c59b5cc7b4ed0de7161ab',
    messagingSenderId: '221510305970',
    projectId: 'flicko-82e0a',
    storageBucket: 'flicko-82e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4cZPSG-oXSFFLh8ejZu3b468rYf9yeM',
    appId: '1:221510305970:ios:07720b04871a1b4c7161ab',
    messagingSenderId: '221510305970',
    projectId: 'flicko-82e0a',
    storageBucket: 'flicko-82e0a.appspot.com',
    iosClientId: '221510305970-rg5k204tja5h3f06dr1h7qmo131180cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flicko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4cZPSG-oXSFFLh8ejZu3b468rYf9yeM',
    appId: '1:221510305970:ios:07720b04871a1b4c7161ab',
    messagingSenderId: '221510305970',
    projectId: 'flicko-82e0a',
    storageBucket: 'flicko-82e0a.appspot.com',
    iosClientId: '221510305970-rg5k204tja5h3f06dr1h7qmo131180cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flicko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq6CiS1IIQmcSjLwvhiu8mvrarKiyURqo',
    appId: '1:221510305970:web:8dc265a26ee502f97161ab',
    messagingSenderId: '221510305970',
    projectId: 'flicko-82e0a',
    authDomain: 'flicko-82e0a.firebaseapp.com',
    storageBucket: 'flicko-82e0a.appspot.com',
  );
}
